# https://rust-lang.github.io/rustfmt
max_width = 79

comment_width = 79
wrap_comments = true

edition = "2021"
format_code_in_doc_comments = true
format_strings = true

normalize_doc_attributes = true
normalize_comments = true

reorder_impl_items = true
reorder_imports = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

use_field_init_shorthand = true
